comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  hide_project_coverage: true

flag_management:
  individual_flags:
    - name: chalk-ts
      paths:
        - src/
      carryforward: true
      statuses:
        - type: project
          target: auto