// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file chalk/server/v1/manager.proto (package chalk.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetClusterEnvironmentsRequest, GetClusterEnvironmentsResponse } from "./manager_pb";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chalk.server.v1.ManagerService
 */
export const ManagerService = {
  typeName: "chalk.server.v1.ManagerService",
  methods: {
    /**
     * If any checks fail, this request fails.
     *
     * @generated from rpc chalk.server.v1.ManagerService.GetClusterEnvironments
     */
    getClusterEnvironments: {
      name: "GetClusterEnvironments",
      I: GetClusterEnvironmentsRequest,
      O: GetClusterEnvironmentsResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
  }
} as const;

