// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file chalk/server/v1/metrics.proto (package chalk.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetOverviewSummaryMetricsRequest, GetOverviewSummaryMetricsResponse } from "./metrics_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chalk.server.v1.MetricsService
 */
export const MetricsService = {
  typeName: "chalk.server.v1.MetricsService",
  methods: {
    /**
     * @generated from rpc chalk.server.v1.MetricsService.GetOverviewSummaryMetrics
     */
    getOverviewSummaryMetrics: {
      name: "GetOverviewSummaryMetrics",
      I: GetOverviewSummaryMetricsRequest,
      O: GetOverviewSummaryMetricsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

