// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file chalk/server/v1/offline_queries.proto (package chalk.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetOfflineQueryRequest, GetOfflineQueryResponse, ListOfflineQueriesRequest, ListOfflineQueriesResponse } from "./offline_queries_pb";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";
import { ListOfflineQueryShardPerformanceSummariesRequest, ListOfflineQueryShardPerformanceSummariesResponse } from "./performance_summary_pb";

/**
 * @generated from service chalk.server.v1.OfflineQueryMetadataService
 */
export const OfflineQueryMetadataService = {
  typeName: "chalk.server.v1.OfflineQueryMetadataService",
  methods: {
    /**
     * @generated from rpc chalk.server.v1.OfflineQueryMetadataService.ListOfflineQueries
     */
    listOfflineQueries: {
      name: "ListOfflineQueries",
      I: ListOfflineQueriesRequest,
      O: ListOfflineQueriesResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * @generated from rpc chalk.server.v1.OfflineQueryMetadataService.GetOfflineQuery
     */
    getOfflineQuery: {
      name: "GetOfflineQuery",
      I: GetOfflineQueryRequest,
      O: GetOfflineQueryResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * @generated from rpc chalk.server.v1.OfflineQueryMetadataService.ListOfflineQueryShardPerformanceSummaries
     */
    listOfflineQueryShardPerformanceSummaries: {
      name: "ListOfflineQueryShardPerformanceSummaries",
      I: ListOfflineQueryShardPerformanceSummariesRequest,
      O: ListOfflineQueryShardPerformanceSummariesResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
  }
} as const;

