// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file chalk/server/v1/webhook.proto (package chalk.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateWebhookRequest, CreateWebhookResponse, DeleteWebhookRequest, DeleteWebhookResponse, GetWebhookRequest, GetWebhookResponse, ListWebhooksRequest, ListWebhooksResponse, UpdateWebhookRequest, UpdateWebhookResponse } from "./webhook_pb";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chalk.server.v1.WebhookService
 */
export const WebhookService = {
  typeName: "chalk.server.v1.WebhookService",
  methods: {
    /**
     * @generated from rpc chalk.server.v1.WebhookService.CreateWebhook
     */
    createWebhook: {
      name: "CreateWebhook",
      I: CreateWebhookRequest,
      O: CreateWebhookResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chalk.server.v1.WebhookService.UpdateWebhook
     */
    updateWebhook: {
      name: "UpdateWebhook",
      I: UpdateWebhookRequest,
      O: UpdateWebhookResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chalk.server.v1.WebhookService.DeleteWebhook
     */
    deleteWebhook: {
      name: "DeleteWebhook",
      I: DeleteWebhookRequest,
      O: DeleteWebhookResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chalk.server.v1.WebhookService.GetWebhook
     */
    getWebhook: {
      name: "GetWebhook",
      I: GetWebhookRequest,
      O: GetWebhookResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * @generated from rpc chalk.server.v1.WebhookService.ListWebhooks
     */
    listWebhooks: {
      name: "ListWebhooks",
      I: ListWebhooksRequest,
      O: ListWebhooksResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
  }
} as const;

