// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=none"
// @generated from file chalk/engine/v2/offline_store_service.proto (package chalk.engine.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message chalk.engine.v2.OfflineStoreServiceDummy
 */
export class OfflineStoreServiceDummy extends Message<OfflineStoreServiceDummy> {
  constructor(data?: PartialMessage<OfflineStoreServiceDummy>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chalk.engine.v2.OfflineStoreServiceDummy";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OfflineStoreServiceDummy {
    return new OfflineStoreServiceDummy().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OfflineStoreServiceDummy {
    return new OfflineStoreServiceDummy().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OfflineStoreServiceDummy {
    return new OfflineStoreServiceDummy().fromJsonString(jsonString, options);
  }

  static equals(a: OfflineStoreServiceDummy | PlainMessage<OfflineStoreServiceDummy> | undefined, b: OfflineStoreServiceDummy | PlainMessage<OfflineStoreServiceDummy> | undefined): boolean {
    return proto3.util.equals(OfflineStoreServiceDummy, a, b);
  }
}

