// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file chalk/server/v1/auth.proto (package chalk.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetTokenRequest, GetTokenResponse, UpdateLinkSessionRequest, UpdateLinkSessionResponse } from "./auth_pb";
import { MethodKind } from "@bufbuild/protobuf";
import { CreateLinkSessionRequest, CreateLinkSessionResponse, GetLinkSessionRequest, GetLinkSessionResponse } from "./link_pb";

/**
 * @generated from service chalk.server.v1.AuthService
 */
export const AuthService = {
  typeName: "chalk.server.v1.AuthService",
  methods: {
    /**
     * @generated from rpc chalk.server.v1.AuthService.GetToken
     */
    getToken: {
      name: "GetToken",
      I: GetTokenRequest,
      O: GetTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chalk.server.v1.AuthService.CreateLinkSession
     */
    createLinkSession: {
      name: "CreateLinkSession",
      I: CreateLinkSessionRequest,
      O: CreateLinkSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chalk.server.v1.AuthService.GetLinkSession
     */
    getLinkSession: {
      name: "GetLinkSession",
      I: GetLinkSessionRequest,
      O: GetLinkSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chalk.server.v1.AuthService.UpdateLinkSession
     */
    updateLinkSession: {
      name: "UpdateLinkSession",
      I: UpdateLinkSessionRequest,
      O: UpdateLinkSessionResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

