// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file chalk/server/v1/chart.proto (package chalk.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListChartsRequest, ListChartsResponse } from "./chart_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chalk.server.v1.ChartsService
 */
export const ChartsService = {
  typeName: "chalk.server.v1.ChartsService",
  methods: {
    /**
     * @generated from rpc chalk.server.v1.ChartsService.ListCharts
     */
    listCharts: {
      name: "ListCharts",
      I: ListChartsRequest,
      O: ListChartsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

