// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file chalk/server/v1/cli.proto (package chalk.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetVersionsRequest, GetVersionsResponse } from "./cli_pb";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chalk.server.v1.CommandLineInterfaceService
 */
export const CommandLineInterfaceService = {
  typeName: "chalk.server.v1.CommandLineInterfaceService",
  methods: {
    /**
     * @generated from rpc chalk.server.v1.CommandLineInterfaceService.GetVersions
     */
    getVersions: {
      name: "GetVersions",
      I: GetVersionsRequest,
      O: GetVersionsResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
  }
} as const;

