// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file chalk/server/v1/flag.proto (package chalk.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetFeatureFlagsRequest, GetFeatureFlagsResponse, SetFeatureFlagRequest, SetFeatureFlagResponse } from "./flag_pb";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chalk.server.v1.FeatureFlagService
 */
export const FeatureFlagService = {
  typeName: "chalk.server.v1.FeatureFlagService",
  methods: {
    /**
     * @generated from rpc chalk.server.v1.FeatureFlagService.GetFeatureFlags
     */
    getFeatureFlags: {
      name: "GetFeatureFlags",
      I: GetFeatureFlagsRequest,
      O: GetFeatureFlagsResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * @generated from rpc chalk.server.v1.FeatureFlagService.SetFeatureFlag
     */
    setFeatureFlag: {
      name: "SetFeatureFlag",
      I: SetFeatureFlagRequest,
      O: SetFeatureFlagResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.Idempotent,
    },
  }
} as const;

