// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file chalk/server/v1/kube.proto (package chalk.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetKubernetesEventsRequest, GetKubernetesEventsResponse, GetKubernetesPersistentVolumesRequest, GetKubernetesPersistentVolumesResponse, GetPodStackTraceDumpRequest, GetPodStackTraceDumpResponse } from "./kube_pb";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chalk.server.v1.KubeService
 */
export const KubeService = {
  typeName: "chalk.server.v1.KubeService",
  methods: {
    /**
     * GetPodStackTraceDump gets the stack trace dump from a single process running in a pod
     * The process can be specified either by name or process ID
     *
     * @generated from rpc chalk.server.v1.KubeService.GetPodStackTraceDump
     */
    getPodStackTraceDump: {
      name: "GetPodStackTraceDump",
      I: GetPodStackTraceDumpRequest,
      O: GetPodStackTraceDumpResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * @generated from rpc chalk.server.v1.KubeService.GetKubernetesEvents
     */
    getKubernetesEvents: {
      name: "GetKubernetesEvents",
      I: GetKubernetesEventsRequest,
      O: GetKubernetesEventsResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * @generated from rpc chalk.server.v1.KubeService.GetKubernetesPersistentVolumes
     */
    getKubernetesPersistentVolumes: {
      name: "GetKubernetesPersistentVolumes",
      I: GetKubernetesPersistentVolumesRequest,
      O: GetKubernetesPersistentVolumesResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
  }
} as const;

