// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file chalk/server/v1/queries.proto (package chalk.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetQueryErrorsChartRequest, GetQueryErrorsChartResponse, GetQueryPerformanceSummaryRequest, GetQueryPerformanceSummaryResponse, ListQueryErrorsRequest, ListQueryErrorsResponse } from "./queries_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chalk.server.v1.QueriesService
 */
export const QueriesService = {
  typeName: "chalk.server.v1.QueriesService",
  methods: {
    /**
     * @generated from rpc chalk.server.v1.QueriesService.GetQueryPerformanceSummary
     */
    getQueryPerformanceSummary: {
      name: "GetQueryPerformanceSummary",
      I: GetQueryPerformanceSummaryRequest,
      O: GetQueryPerformanceSummaryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chalk.server.v1.QueriesService.ListQueryErrors
     */
    listQueryErrors: {
      name: "ListQueryErrors",
      I: ListQueryErrorsRequest,
      O: ListQueryErrorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc chalk.server.v1.QueriesService.GetQueryErrorsChart
     */
    getQueryErrorsChart: {
      name: "GetQueryErrorsChart",
      I: GetQueryErrorsChartRequest,
      O: GetQueryErrorsChartResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

