// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=none"
// @generated from file chalk/server/v1/scheduled_query.proto (package chalk.server.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetScheduledQueryRunRequest, GetScheduledQueryRunResponse } from "./scheduled_query_run_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service chalk.server.v1.ScheduledQueryService
 */
export const ScheduledQueryService = {
  typeName: "chalk.server.v1.ScheduledQueryService",
  methods: {
    /**
     * @generated from rpc chalk.server.v1.ScheduledQueryService.GetScheduledQueryRun
     */
    getScheduledQueryRun: {
      name: "GetScheduledQueryRun",
      I: GetScheduledQueryRunRequest,
      O: GetScheduledQueryRunResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

