name: check
on:
  push:
    branches: [main]
  pull_request: {}
  workflow_dispatch: {}

jobs:
  yarn-installs-cleanly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: yarn
      - run: yarn install --immutable

  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: yarn
      - run: yarn install

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: yarn
      - run: yarn install
      - run: yarn build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: yarn
      - run: yarn install
      - run: yarn test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: chalk-ts

  integration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: yarn
      - run: yarn install
      - run: yarn test:integration
        env:
          CI_CHALK_CLIENT_ID: ${{ secrets.CHALK_CLIENT_ID }}
          CI_CHALK_CLIENT_SECRET: ${{ secrets.CHALK_CLIENT_SECRET }}
          _INTEGRATION_TEST_CLIENT_ID: ${{ secrets._INTEGRATION_TEST_CLIENT_ID }}
          _INTEGRATION_TEST_CLIENT_SECRET: ${{ secrets._INTEGRATION_TEST_CLIENT_SECRET }}
          _INTEGRATION_TEST_API_SERVER: ${{ secrets._INTEGRATION_TEST_API_SERVER }}
          _INTEGRATION_TEST_ACTIVE_ENVIRONMENT: ${{ secrets._INTEGRATION_TEST_ACTIVE_ENVIRONMENT }}
